
package org.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "UserWebServiceService", targetNamespace = "http://example.org/", wsdlLocation = "http://localhost:8080/ws/user?wsdl")
public class UserWebServiceService
    extends Service
{

    private final static URL USERWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException USERWEBSERVICESERVICE_EXCEPTION;
    private final static QName USERWEBSERVICESERVICE_QNAME = new QName("http://example.org/", "UserWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ws/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERWEBSERVICESERVICE_WSDL_LOCATION = url;
        USERWEBSERVICESERVICE_EXCEPTION = e;
    }

    public UserWebServiceService() {
        super(__getWsdlLocation(), USERWEBSERVICESERVICE_QNAME);
    }

    public UserWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERWEBSERVICESERVICE_QNAME, features);
    }

    public UserWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, USERWEBSERVICESERVICE_QNAME);
    }

    public UserWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERWEBSERVICESERVICE_QNAME, features);
    }

    public UserWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserWebService
     */
    @WebEndpoint(name = "UserWebServicePort")
    public UserWebService getUserWebServicePort() {
        return super.getPort(new QName("http://example.org/", "UserWebServicePort"), UserWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserWebService
     */
    @WebEndpoint(name = "UserWebServicePort")
    public UserWebService getUserWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example.org/", "UserWebServicePort"), UserWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERWEBSERVICESERVICE_EXCEPTION!= null) {
            throw USERWEBSERVICESERVICE_EXCEPTION;
        }
        return USERWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
