
package org.example.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 4.0.0-M4
 * Generated source version: 3.0
 * 
 */
@WebService(name = "UserWebService", targetNamespace = "http://example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebService {


    /**
     * 
     * @param phone
     * @param username
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "guiThongTin", targetNamespace = "http://example.org/", className = "org.example.client.GuiThongTin")
    @ResponseWrapper(localName = "guiThongTinResponse", targetNamespace = "http://example.org/", className = "org.example.client.GuiThongTinResponse")
    @Action(input = "http://example.org/UserWebService/guiThongTinRequest", output = "http://example.org/UserWebService/guiThongTinResponse")
    public String guiThongTin(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "phone", targetNamespace = "")
        String phone);

}
